### PR TITLE
Mark Oliver display characters

### PR DESCRIPTION
**Pull request by invegat**

### CODE REVIEW

**Review by ely-alamillo — APPROVED** [review]
Hey Mark, this looks good to me. I didn't see you submitted a link to the deploy. I encourage you to add the link and if you weren't able to deploy you should give it a shot and see how far you can get.

**Comment by invegat** [comment]
https://lambda-django-rpg.herokuapp.com, sorry should have submitted that somewhere.

**Comment by ely-alamillo** [comment]
No worries!

The deploy looks good and I like how it takes you to the graphQL page. For the purpose of this app that is okay. It would be better if the landing page would be something else. Other than that good job!

**Comment by invegat** [comment]
Thanks!   I am bummed that I didn't have more time to figure out to use the
graphIQL page.   The next cohorts wouldn't waste time like we did and
wouldn't be as pathetic as us.

**Comment by agallant** [comment]
This was the first offering so there were some rough edges, but I don't think this cohort was in any way "pathetic" - and GraphQL is somewhat cutting edge/unstable, especially in the Python universe.

**Comment by invegat** [comment]
GraphIQL has a  100% completely different interface than GraphQL, no
capabilities except what the programmer gives it.

**Comment by invegat** [comment]
The programmer makes custom applications.

**Comment by invegat** [comment]
http://graphql.org/swapi-graphql/

**Comment by invegat** [comment]
{
  person(personID: 3) {
    name
  }
}

**Comment by agallant** [comment]
These sorts of limitations and caveats come with the territory for "cutting edge" tech/libraries - it's good that you explored them, but I do think that ultimately what we want is to defer to GraphiQL rather than hack it ourselves. Hopefully graphene gets to a point where more things are "hooked up" intuitively (or at least it's clearer how to do so).

**Comment by invegat** [comment]
https://github.com/graphql-python/swapi-graphene

**Comment by invegat** [comment]
python3 version https://github.com/invegat/swapi-graphene

**Pull request closed without merging**
